import math
import tempfile
import xml.etree.ElementTree as ET
from pathlib import Path

import torch
from tensordict import TensorDict

import genesis as gs
from genesis.utils.geom import inv_quat, quat_to_xyz, transform_by_quat, transform_quat_by_quat


ASSET_DIR = Path(__file__).resolve().parents[2] / "genesis" / "assets" / "xml" / "unitree_g1"


def _read_obj_vertices(path):
    verts = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("v "):
                _, x, y, z, *_ = line.split()
                verts.append((float(x), float(y), float(z)))
    return torch.tensor(verts, dtype=gs.tc_float, device=gs.device)


def _read_mjcf_joint_ranges(path):
    tree = ET.parse(path)
    ranges = {}
    for joint in tree.getroot().findall(".//joint[@name][@range]"):
        lower, upper = joint.attrib["range"].split()
        ranges[joint.attrib["name"]] = (float(lower), float(upper))
    return ranges


def _single_mesh_obj(path):
    """PBD entities accept one mesh; merge OBJ material groups while preserving vertex order."""
    out_dir = Path(tempfile.gettempdir()) / "genesis_trampoline"
    out_dir.mkdir(parents=True, exist_ok=True)
    src_mtime = path.stat().st_mtime
    out = out_dir / f"{path.stem}_{int(src_mtime)}_singlemesh.obj"
    if out.exists() and out.stat().st_mtime >= src_mtime:
        return out

    kept = []
    with open(path, encoding="utf-8") as f:
        for line in f:
            if line.startswith("v ") or line.startswith("f "):
                kept.append(line)
    with open(out, "w", encoding="utf-8") as f:
        f.write("# Generated by examples/trampoline/trampoline_env.py for PBD cloth loading.\n")
        f.writelines(kept)
    return out


def _trampoline_contact_mjcf(path, foot_radius=0.025):
    """Create a temporary G1 MJCF with foot contact patches large enough for particle cloth contact."""
    out_dir = Path(tempfile.gettempdir()) / "genesis_trampoline"
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / f"{path.stem}_footpatch_r{int(foot_radius * 1000)}.xml"
    if out.exists() and out.stat().st_mtime >= path.stat().st_mtime:
        return out

    tree = ET.parse(path)
    root = tree.getroot()
    compiler = root.find("compiler")
    if compiler is not None:
        compiler.set("meshdir", str((path.parent / "assets").resolve()).replace("\\", "/"))

    for default in root.findall(".//default[@class='foot']"):
        geom = default.find("geom")
        if geom is not None:
            geom.set("size", str(foot_radius))

    patches = {
        "left_ankle_roll_link": "left",
        "right_ankle_roll_link": "right",
    }
    for body in root.findall(".//body"):
        side = patches.get(body.attrib.get("name"))
        if side is None:
            continue

        ET.SubElement(
            body,
            "geom",
            {
                "name": f"{side}_foot_box_trampoline_collision",
                "class": "collision",
                "type": "box",
                "pos": "0.04 0 -0.035",
                "size": "0.11 0.045 0.014",
                "friction": "0.9",
                "condim": "3",
                "group": "4",
                "rgba": "0 0.8 0 0.35",
            },
        )
        ET.SubElement(
            body,
            "geom",
            {
                "name": f"{side}_foot_capsule_trampoline_collision",
                "class": "collision",
                "type": "capsule",
                "fromto": "-0.055 0 -0.032 0.14 0 -0.032",
                "size": "0.025",
                "friction": "0.9",
                "condim": "3",
                "group": "4",
                "rgba": "0 0.8 0 0.25",
            },
        )

    tree.write(out, encoding="utf-8", xml_declaration=False)
    return out


class G1TrampolineEnv:
    def __init__(self, num_envs, env_cfg, obs_cfg, reward_cfg, command_cfg, show_viewer=False):
        env_cfg = dict(env_cfg)
        env_cfg.setdefault("trampoline_self_collision", False)
        env_cfg.setdefault("trampoline_rigid_friction", True)
        env_cfg.setdefault("control_decimation", 1)
        env_cfg["pbd_bending_iterations"] = 0

        self.num_envs = num_envs
        self.num_actions = env_cfg["num_actions"]
        self.cfg = env_cfg
        self.env_cfg = env_cfg
        self.obs_cfg = obs_cfg
        self.reward_cfg = reward_cfg
        self.command_cfg = command_cfg
        self.device = gs.device

        self.sim_dt = env_cfg["dt"]
        self.control_decimation = env_cfg["control_decimation"]
        self.dt = self.sim_dt * self.control_decimation
        self.max_episode_length = math.ceil(env_cfg["episode_length_s"] / self.dt)
        self.simulate_action_latency = env_cfg["simulate_action_latency"]
        self.obs_scales = obs_cfg["obs_scales"]
        self.reward_scales = reward_cfg["reward_scales"]

        trampoline_file = env_cfg["trampoline_file"]
        trampoline_path = ASSET_DIR / trampoline_file
        trampoline_pbd_path = _single_mesh_obj(trampoline_path)
        ring_count = env_cfg["outer_ring_vertex_counts"][trampoline_file]
        self.trampoline_ring_idx = torch.arange(ring_count, dtype=gs.tc_int, device=gs.device)
        trampoline_vertices = _read_obj_vertices(trampoline_path)
        self.trampoline_ring_targets = trampoline_vertices[:ring_count]
        trampoline_radius = torch.linalg.norm(trampoline_vertices[:, :2], dim=-1)
        trampoline_ring_radius = torch.linalg.norm(self.trampoline_ring_targets[:, :2], dim=-1).mean()
        center_vertices = trampoline_vertices[trampoline_radius < env_cfg["trampoline_center_radius"]]
        trampoline_stand_z = (
            center_vertices[:, 2].mean() if len(center_vertices) > 0 else trampoline_vertices[:, 2].mean()
        )
        self.trampoline_surface_z = float(trampoline_stand_z.item())
        base_init_pos = list(env_cfg["base_init_pos"])
        if env_cfg["base_init_pos_relative_to_trampoline"]:
            base_init_pos[2] += self.trampoline_surface_z + env_cfg["base_init_clearance"]

        self.scene = gs.Scene(
            sim_options=gs.options.SimOptions(
                dt=self.sim_dt,
                substeps=env_cfg["substeps"],
                gravity=(0.0, 0.0, -9.81),
            ),
            rigid_options=gs.options.RigidOptions(
                enable_self_collision=False,
                max_collision_pairs=env_cfg["max_collision_pairs"],
                constraint_timeconst=env_cfg["constraint_timeconst"],
            ),
            pbd_options=gs.options.PBDOptions(
                particle_size=env_cfg["trampoline_particle_size"],
                enable_self_collision=env_cfg["trampoline_self_collision"],
                enable_rigid_friction=env_cfg["trampoline_rigid_friction"],
                lower_bound=(-2.0, -2.0, -0.2),
                upper_bound=(2.0, 2.0, 2.2),
                max_stretch_solver_iterations=env_cfg["pbd_stretch_iterations"],
                max_bending_solver_iterations=env_cfg["pbd_bending_iterations"],
            ),
            coupler_options=gs.options.LegacyCouplerOptions(
                rigid_pbd=env_cfg["enable_robot_trampoline_coupling"],
            ),
            profiling_options=gs.options.ProfilingOptions(show_FPS=False),
            viewer_options=gs.options.ViewerOptions(
                camera_pos=(2.8, -3.0, 1.7),
                camera_lookat=(0.0, 0.0, 0.75),
                camera_fov=35,
            ),
            vis_options=gs.options.VisOptions(
                rendered_envs_idx=[0],
                background_color=env_cfg["sky_background_color"],
                ambient_light=env_cfg["ambient_light"],
                plane_reflection=env_cfg["ground_reflection"],
            ),
            show_viewer=show_viewer,
        )

        self.ground = None
        if env_cfg["show_ground"]:
            self.ground = self.scene.add_entity(
                morph=gs.morphs.Plane(
                    pos=(0.0, 0.0, env_cfg["ground_z"]),
                    plane_size=env_cfg["ground_size"],
                    tile_size=env_cfg["ground_tile_size"],
                    visualization=True,
                    collision=env_cfg["ground_collision"],
                ),
                material=gs.materials.Rigid(
                    friction=env_cfg["ground_friction"],
                    needs_coup=False,
                ),
                surface=gs.surfaces.Default(color=env_cfg["ground_color"]),
            )

        self.trampoline_support = None
        if env_cfg["enable_trampoline_support"]:
            support_height = env_cfg["trampoline_support_height"]
            support_top_z = self.trampoline_surface_z + env_cfg["trampoline_support_top_offset"]
            support_radius = min(
                env_cfg["trampoline_support_radius"],
                float(trampoline_ring_radius.item()) - env_cfg["trampoline_support_edge_margin"],
            )
            self.trampoline_support = self.scene.add_entity(
                morph=gs.morphs.Cylinder(
                    radius=support_radius,
                    height=support_height,
                    pos=(0.0, 0.0, support_top_z - 0.5 * support_height),
                    fixed=True,
                    visualization=env_cfg["trampoline_support_visualization"],
                    collision=True,
                ),
                material=gs.materials.Rigid(
                    friction=env_cfg["trampoline_support_friction"],
                    needs_coup=False,
                ),
                surface=gs.surfaces.Default(color=(0.06, 0.06, 0.06, 0.25)),
            )

        robot_needs_coup = env_cfg["enable_robot_trampoline_coupling"]
        rigid_mat = gs.materials.Rigid(
            friction=env_cfg["robot_friction"],
            needs_coup=robot_needs_coup,
            coup_friction=env_cfg["robot_coup_friction"],
            coup_softness=env_cfg["robot_coup_softness"],
            coup_links=env_cfg["robot_coup_links"] if robot_needs_coup else None,
        )
        robot_mjcf_path = ASSET_DIR / env_cfg["robot_mjcf"]
        robot_file = (
            str(_trampoline_contact_mjcf(robot_mjcf_path, env_cfg["robot_foot_radius"]))
            if env_cfg["use_trampoline_contact_mjcf"]
            else env_cfg["robot_mjcf"]
        )
        self.robot_joint_ranges = _read_mjcf_joint_ranges(robot_mjcf_path)

        self.robot = self.scene.add_entity(
            morph=gs.morphs.MJCF(
                file=robot_file,
                pos=base_init_pos,
                quat=env_cfg["base_init_quat"],
            ),
            material=rigid_mat,
        )
        self.trampoline = self.scene.add_entity(
            morph=gs.morphs.Mesh(
                file=str(trampoline_pbd_path),
                pos=(0.0, 0.0, 0.0),
                scale=1.0,
            ),
            material=gs.materials.PBD.Cloth(
                rho=env_cfg["trampoline_rho"],
                static_friction=env_cfg["trampoline_static_friction"],
                kinetic_friction=env_cfg["trampoline_kinetic_friction"],
                stretch_compliance=env_cfg["trampoline_stretch_compliance"],
                bending_compliance=env_cfg["trampoline_bending_compliance"],
                stretch_relaxation=env_cfg["trampoline_stretch_relaxation"],
                bending_relaxation=env_cfg["trampoline_bending_relaxation"],
                air_resistance=env_cfg["trampoline_air_resistance"],
            ),
            surface=gs.surfaces.Default(color=(0.08, 0.28, 0.75, 0.55), vis_mode="visual"),
        )

        self.scene.build(n_envs=num_envs)

        self.motors_dof_idx = torch.tensor(
            [self.robot.get_joint(name).dof_start for name in env_cfg["joint_names"]],
            dtype=gs.tc_int,
            device=gs.device,
        )
        self.locked_dof_idx = torch.tensor(
            [self.robot.get_joint(name).dof_start for name in env_cfg["locked_joint_names"]],
            dtype=gs.tc_int,
            device=gs.device,
        )
        self.all_actuated_dof_idx = torch.cat((self.motors_dof_idx, self.locked_dof_idx))
        self.actions_dof_idx = torch.argsort(self.motors_dof_idx)
        self.feet_link_idx = torch.tensor(
            [self.robot.get_link(name).idx_local for name in env_cfg["feet_link_names"]],
            dtype=gs.tc_int,
            device=gs.device,
        )

        kp = self._get_joint_cfg_values("kp")
        kd = self._get_joint_cfg_values("kd")
        self.robot.set_dofs_kp(kp, self.motors_dof_idx)
        self.robot.set_dofs_kv(kd, self.motors_dof_idx)
        if len(self.locked_dof_idx) > 0:
            lock_kp = self._get_joint_cfg_values("lock_kp", env_cfg["locked_joint_names"])
            lock_kd = self._get_joint_cfg_values("lock_kd", env_cfg["locked_joint_names"])
            self.robot.set_dofs_kp(lock_kp, self.locked_dof_idx)
            self.robot.set_dofs_kv(lock_kd, self.locked_dof_idx)

        self.default_dof_pos = torch.tensor(
            [env_cfg["default_joint_angles"][name] for name in env_cfg["joint_names"]],
            dtype=gs.tc_float,
            device=gs.device,
        )
        action_scales = env_cfg.get("action_scales")
        if action_scales is None and env_cfg.get("action_scale_from_joint_limits", False):
            action_scales = self._get_action_scales_from_joint_limits()
        if action_scales is None:
            action_scales = env_cfg["action_scale"]
        if isinstance(action_scales, dict):
            action_scales = [action_scales[name] for name in env_cfg["joint_names"]]
        self.action_scales = torch.as_tensor(action_scales, dtype=gs.tc_float, device=gs.device)
        if self.action_scales.ndim == 0:
            self.action_scales = self.action_scales.repeat(self.num_actions)
        if self.action_scales.shape != (self.num_actions,):
            raise ValueError(f"action_scales must have shape ({self.num_actions},), got {tuple(self.action_scales.shape)}")
        self.reward_dof_weights = {
            name: torch.tensor(
                self._get_joint_cfg_values(name, env_cfg["joint_names"]),
                dtype=gs.tc_float,
                device=gs.device,
            )
            for name in ("action_rate_weights", "dof_vel_weights", "similar_to_default_weights")
        }
        self.locked_default_dof_pos = torch.tensor(
            [env_cfg["default_joint_angles"][name] for name in env_cfg["locked_joint_names"]],
            dtype=gs.tc_float,
            device=gs.device,
        )
        init_all_dofs = torch.tensor(
            [env_cfg["default_joint_angles"][joint.name] for joint in self.robot.joints[1:]],
            dtype=gs.tc_float,
            device=gs.device,
        )
        self.init_base_pos = torch.tensor(base_init_pos, dtype=gs.tc_float, device=gs.device)
        self.init_base_quat = torch.tensor(env_cfg["base_init_quat"], dtype=gs.tc_float, device=gs.device)
        self.inv_base_init_quat = inv_quat(self.init_base_quat)
        self.init_qpos = torch.cat((self.init_base_pos, self.init_base_quat, init_all_dofs))

        self.global_gravity = torch.tensor([0.0, 0.0, -1.0], dtype=gs.tc_float, device=gs.device)
        self.init_projected_gravity = transform_by_quat(self.global_gravity, self.inv_base_init_quat)
        self.base_height_ref = self.init_base_pos[2].clone()
        self.flight_height_target = reward_cfg["flight_height_target"]

        self.base_pos = torch.empty((num_envs, 3), dtype=gs.tc_float, device=gs.device)
        self.base_quat = torch.empty((num_envs, 4), dtype=gs.tc_float, device=gs.device)
        self.base_euler = torch.empty((num_envs, 3), dtype=gs.tc_float, device=gs.device)
        self.base_lin_vel = torch.empty((num_envs, 3), dtype=gs.tc_float, device=gs.device)
        self.base_ang_vel = torch.empty((num_envs, 3), dtype=gs.tc_float, device=gs.device)
        self.projected_gravity = torch.empty((num_envs, 3), dtype=gs.tc_float, device=gs.device)
        self.feet_pos = torch.empty((num_envs, len(env_cfg["feet_link_names"]), 3), dtype=gs.tc_float, device=gs.device)
        self.feet_cloth_obs = torch.zeros((num_envs, 4), dtype=gs.tc_float, device=gs.device)
        self.dof_pos = torch.empty((num_envs, self.num_actions), dtype=gs.tc_float, device=gs.device)
        self.dof_vel = torch.empty((num_envs, self.num_actions), dtype=gs.tc_float, device=gs.device)
        self.last_dof_vel = torch.zeros_like(self.dof_vel)
        self.actions = torch.zeros((num_envs, self.num_actions), dtype=gs.tc_float, device=gs.device)
        self.last_actions = torch.zeros_like(self.actions)
        self.rew_buf = torch.zeros((num_envs,), dtype=gs.tc_float, device=gs.device)
        self.reset_buf = torch.ones((num_envs,), dtype=gs.tc_bool, device=gs.device)
        self.episode_length_buf = torch.zeros((num_envs,), dtype=gs.tc_int, device=gs.device)
        self.max_height_buf = torch.zeros((num_envs,), dtype=gs.tc_float, device=gs.device)
        self.jump_success_buf = torch.zeros((num_envs,), dtype=gs.tc_float, device=gs.device)
        self.extras = {}

        self._fix_trampoline_outer_ring()

        self.reward_functions, self.episode_sums = {}, {}
        for name in self.reward_scales:
            self.reward_scales[name] *= self.dt
            self.reward_functions[name] = getattr(self, "_reward_" + name)
            self.episode_sums[name] = torch.zeros((num_envs,), dtype=gs.tc_float, device=gs.device)

        self.reset()

    def _get_joint_cfg_values(self, name, joint_names=None):
        if joint_names is None:
            joint_names = self.env_cfg["joint_names"]
        value = self.env_cfg[name]
        if isinstance(value, dict):
            return [value[joint_name] for joint_name in joint_names]
        return [value] * len(joint_names)

    def _get_action_scales_from_joint_limits(self):
        scales = []
        safety = self.env_cfg["action_scale_safety"]
        limits = self.env_cfg.get("action_scale_limits", {})
        for joint_name in self.env_cfg["joint_names"]:
            lower, upper = self.robot_joint_ranges[joint_name]
            default = self.env_cfg["default_joint_angles"][joint_name]
            scale = safety * min(default - lower, upper - default)
            scale = min(scale, limits.get(joint_name, float("inf")))
            scales.append(scale)
        return scales

    def _fix_trampoline_outer_ring(self):
        particles = self.trampoline.get_particles_pos()
        if particles.ndim == 3:
            particles = particles[0]
        fixed = set()
        for target in self.trampoline_ring_targets:
            fixed.add(int(torch.argmin(torch.linalg.norm(particles - target, dim=-1)).item()))

        ring_radius = torch.linalg.norm(self.trampoline_ring_targets[:, :2], dim=-1).mean()
        particle_radius = torch.linalg.norm(particles[:, :2], dim=-1)
        boundary_idx = torch.nonzero(
            particle_radius >= ring_radius - self.env_cfg["trampoline_outer_fix_width"],
            as_tuple=False,
        ).flatten()
        fixed.update(int(i) for i in boundary_idx.detach().cpu().tolist())
        self.trampoline_fixed_particles = sorted(set(fixed))
        fixed_idx = torch.tensor(self.trampoline_fixed_particles, dtype=gs.tc_int, device=gs.device)
        self.trampoline.fix_particles(fixed_idx)

    def step(self, actions):
        self.actions = torch.clip(actions, -self.env_cfg["clip_actions"], self.env_cfg["clip_actions"])
        exec_actions = self.last_actions if self.simulate_action_latency else self.actions
        target_dof_pos = exec_actions * self.action_scales + self.default_dof_pos
        self.robot.control_dofs_position(target_dof_pos[:, self.actions_dof_idx], self.motors_dof_idx)
        if len(self.locked_dof_idx) > 0:
            self.robot.control_dofs_position(self.locked_default_dof_pos.expand(self.num_envs, -1), self.locked_dof_idx)

        for _ in range(self.control_decimation):
            self.scene.step()

        self.episode_length_buf += 1
        self._refresh_state()

        height_above_ref = self.base_pos[:, 2] - self.base_height_ref
        self.max_height_buf = torch.maximum(self.max_height_buf, height_above_ref)
        self.jump_success_buf = torch.maximum(
            self.jump_success_buf, (height_above_ref > self.flight_height_target).float()
        )

        self.rew_buf.zero_()
        for name, reward_func in self.reward_functions.items():
            rew = reward_func() * self.reward_scales[name]
            self.rew_buf += rew
            self.episode_sums[name] += rew

        self.reset_buf = self.episode_length_buf > self.max_episode_length
        self.reset_buf |= torch.abs(self.base_euler[:, 0]) > self.env_cfg["termination_if_roll_greater_than"]
        self.reset_buf |= torch.abs(self.base_euler[:, 1]) > self.env_cfg["termination_if_pitch_greater_than"]
        self.reset_buf |= (
            torch.linalg.norm(self.base_pos[:, :2], dim=-1) > self.env_cfg["termination_if_xy_greater_than"]
        )
        self.reset_buf |= self.base_pos[:, 2] < self.env_cfg["termination_if_base_lower_than"]
        self.reset_buf |= self.scene.rigid_solver.get_error_envs_mask()
        self.extras["time_outs"] = (self.episode_length_buf > self.max_episode_length).to(gs.tc_float)

        self._reset_idx(self.reset_buf)
        self._update_observation()

        self.last_actions.copy_(self.actions)
        self.last_dof_vel.copy_(self.dof_vel)
        return self.get_observations(), self.rew_buf, self.reset_buf, self.extras

    def _refresh_state(self):
        self.base_pos = self.robot.get_pos()
        self.base_quat = self.robot.get_quat()
        self.base_euler = quat_to_xyz(
            transform_quat_by_quat(self.inv_base_init_quat, self.base_quat), rpy=True, degrees=True
        )
        inv_base_quat = inv_quat(self.base_quat)
        self.base_lin_vel = transform_by_quat(self.robot.get_vel(), inv_base_quat)
        self.base_ang_vel = transform_by_quat(self.robot.get_ang(), inv_base_quat)
        self.projected_gravity = transform_by_quat(self.global_gravity, inv_base_quat)
        self.feet_pos = self.robot.get_links_pos(self.feet_link_idx)
        self._refresh_feet_cloth_obs()
        self.dof_pos = self.robot.get_dofs_position(self.motors_dof_idx)
        self.dof_vel = self.robot.get_dofs_velocity(self.motors_dof_idx)
    def _refresh_feet_cloth_obs(self):
        particles_pos = self.trampoline.get_particles_pos()
        particles_vel = self.trampoline.get_particles_vel()
        foot_xy = self.feet_pos[..., :2]
        delta_xy = particles_pos[:, None, :, :2] - foot_xy[:, :, None, :]
        dist2 = torch.sum(torch.square(delta_xy), dim=-1)
        radius = self.env_cfg["feet_cloth_obs_radius"]
        weights = torch.exp(-dist2 / max(radius * radius, gs.EPS))
        weights = weights / torch.clamp(weights.sum(dim=-1, keepdim=True), min=gs.EPS)
        cloth_z = torch.sum(weights * particles_pos[:, None, :, 2], dim=-1)
        cloth_vz = torch.sum(weights * particles_vel[:, None, :, 2], dim=-1)
        rel_height = self.feet_pos[..., 2] - cloth_z
        self.feet_cloth_obs = torch.cat(
            (
                rel_height * self.obs_scales["feet_cloth_height"],
                cloth_vz * self.obs_scales["feet_cloth_vel_z"],
            ),
            dim=-1,
        )

    def get_observations(self):
        return TensorDict({"policy": self.obs_buf}, batch_size=[self.num_envs])

    def _reset_idx(self, envs_idx=None):
        episode_max_height = self.max_height_buf.clone()
        episode_success = self.jump_success_buf.clone()

        self.robot.set_qpos(self.init_qpos, envs_idx=envs_idx, zero_velocity=True, skip_forward=True)
        if envs_idx is None:
            self.trampoline.set_position(self.trampoline._particles)
            self.trampoline.set_velocity(0.0)
            self.trampoline.process_input()
            self.trampoline.fix_particles(self.trampoline_fixed_particles)
            self.base_pos.copy_(self.init_base_pos)
            self.base_quat.copy_(self.init_base_quat)
            self.projected_gravity.copy_(self.init_projected_gravity)
            self.base_lin_vel.zero_()
            self.base_ang_vel.zero_()
            self.dof_pos.copy_(self.default_dof_pos)
            self.dof_vel.zero_()
            self.actions.zero_()
            self.last_actions.zero_()
            self.last_dof_vel.zero_()
            self.episode_length_buf.zero_()
            self.max_height_buf.zero_()
            self.jump_success_buf.zero_()
            self.reset_buf.fill_(True)
        else:
            self.base_pos[envs_idx] = self.init_base_pos
            self.base_quat[envs_idx] = self.init_base_quat
            self.projected_gravity[envs_idx] = self.init_projected_gravity
            self.base_lin_vel.masked_fill_(envs_idx[:, None], 0.0)
            self.base_ang_vel.masked_fill_(envs_idx[:, None], 0.0)
            self.dof_pos[envs_idx] = self.default_dof_pos
            self.dof_vel.masked_fill_(envs_idx[:, None], 0.0)
            self.actions.masked_fill_(envs_idx[:, None], 0.0)
            self.last_actions.masked_fill_(envs_idx[:, None], 0.0)
            self.last_dof_vel.masked_fill_(envs_idx[:, None], 0.0)
            self.episode_length_buf.masked_fill_(envs_idx, 0)
            self.max_height_buf.masked_fill_(envs_idx, 0.0)
            self.jump_success_buf.masked_fill_(envs_idx, 0.0)
            self.reset_buf.masked_fill_(envs_idx, True)

        n_envs = envs_idx.sum() if envs_idx is not None else self.num_envs
        self.extras["episode"] = {
            "max_jump_height": episode_max_height.mean()
            if envs_idx is None
            else torch.where(n_envs > 0, episode_max_height[envs_idx].sum() / n_envs, 0.0),
            "jump_success_rate": episode_success.mean()
            if envs_idx is None
            else torch.where(n_envs > 0, episode_success[envs_idx].sum() / n_envs, 0.0),
        }
        for key, value in self.episode_sums.items():
            mean = value.mean() if envs_idx is None else torch.where(n_envs > 0, value[envs_idx].sum() / n_envs, 0.0)
            self.extras["episode"]["rew_" + key] = mean / self.env_cfg["episode_length_s"]
            if envs_idx is None:
                value.zero_()
            else:
                value.masked_fill_(envs_idx, 0.0)
    def _update_observation(self):
        self.obs_buf = torch.cat(
            (
                self.base_ang_vel * self.obs_scales["ang_vel"],
                self.projected_gravity,
                (self.base_pos[:, 2:3] - self.base_height_ref) * self.obs_scales["height"],
                self.base_lin_vel[:, 2:3] * self.obs_scales["lin_vel_z"],
                self.base_pos[:, :2] * self.obs_scales["xy"],
                self.feet_cloth_obs,
                (self.dof_pos - self.default_dof_pos) * self.obs_scales["dof_pos"],
                self.dof_vel * self.obs_scales["dof_vel"],
                self.actions,
            ),
            dim=-1,
        )

    def reset(self):
        self._reset_idx()
        self._update_observation()
        return self.get_observations()

    def _reward_jump_height(self):
        h = self.base_pos[:, 2] - self.base_height_ref
        return torch.exp(-torch.square((h - self.flight_height_target) / self.reward_cfg["height_tracking_sigma"]))

    def _reward_air_time_apex(self):
        h = self.base_pos[:, 2] - self.base_height_ref
        up = torch.clamp(h / self.flight_height_target, 0.0, 1.5)
        near_apex = torch.exp(-torch.square(self.base_lin_vel[:, 2] / self.reward_cfg["apex_vel_sigma"]))
        return up * near_apex

    def _reward_vertical_velocity(self):
        desired = self.reward_cfg["takeoff_vel"]
        return torch.exp(-torch.square((self.base_lin_vel[:, 2] - desired) / self.reward_cfg["vel_tracking_sigma"]))

    def _reward_centering(self):
        return torch.exp(-torch.sum(torch.square(self.base_pos[:, :2]), dim=-1) / self.reward_cfg["centering_sigma"])

    def _reward_upright(self):
        return torch.sum(torch.square(self.projected_gravity[:, :2]), dim=-1)

    def _reward_action_rate(self):
        return torch.sum(
            self.reward_dof_weights["action_rate_weights"] * torch.square(self.actions - self.last_actions),
            dim=-1,
        )

    def _reward_dof_acc(self):
        return torch.sum(torch.square((self.dof_vel - self.last_dof_vel) / self.dt), dim=-1)

    def _reward_similar_to_default(self):
        return torch.sum(
            self.reward_dof_weights["similar_to_default_weights"] * torch.square(self.dof_pos - self.default_dof_pos),
            dim=-1,
        )

    def _reward_alive(self):
        return torch.ones((self.num_envs,), dtype=gs.tc_float, device=gs.device)

    def _reward_standing_height(self):
        target_height = self.base_height_ref + self.reward_cfg["standing_height_offset"]
        height_error = self.base_pos[:, 2] - target_height
        return torch.exp(-torch.square(height_error / self.reward_cfg["standing_height_sigma"]))

    def _reward_lin_vel_xy(self):
        return torch.sum(torch.square(self.base_lin_vel[:, :2]), dim=-1)

    def _reward_lin_vel_z(self):
        return torch.square(self.base_lin_vel[:, 2])

    def _reward_ang_vel_xy(self):
        return torch.sum(torch.square(self.base_ang_vel[:, :2]), dim=-1)

    def _reward_dof_vel(self):
        return torch.sum(self.reward_dof_weights["dof_vel_weights"] * torch.square(self.dof_vel), dim=-1)


def get_default_cfgs():
    leg_joints = [
        "left_hip_pitch_joint",
        "left_hip_roll_joint",
        "left_hip_yaw_joint",
        "left_knee_joint",
        "left_ankle_pitch_joint",
        "left_ankle_roll_joint",
        "right_hip_pitch_joint",
        "right_hip_roll_joint",
        "right_hip_yaw_joint",
        "right_knee_joint",
        "right_ankle_pitch_joint",
        "right_ankle_roll_joint",
    ]
    upper_joints = [
        "waist_yaw_joint",
        "waist_roll_joint",
        "waist_pitch_joint",
        "left_shoulder_pitch_joint",
        "left_shoulder_roll_joint",
        "left_shoulder_yaw_joint",
        "left_elbow_joint",
        "left_wrist_roll_joint",
        "left_wrist_pitch_joint",
        "left_wrist_yaw_joint",
        "right_shoulder_pitch_joint",
        "right_shoulder_roll_joint",
        "right_shoulder_yaw_joint",
        "right_elbow_joint",
        "right_wrist_roll_joint",
        "right_wrist_pitch_joint",
        "right_wrist_yaw_joint",
    ]
    default_joint_angles = {
        "left_hip_pitch_joint": -0.18,
        "left_hip_roll_joint": 0.0,
        "left_hip_yaw_joint": 0.0,
        "left_knee_joint": 0.42,
        "left_ankle_pitch_joint": -0.24,
        "left_ankle_roll_joint": 0.0,
        "right_hip_pitch_joint": -0.18,
        "right_hip_roll_joint": 0.0,
        "right_hip_yaw_joint": 0.0,
        "right_knee_joint": 0.42,
        "right_ankle_pitch_joint": -0.24,
        "right_ankle_roll_joint": 0.0,
        "waist_yaw_joint": 0.0,
        "waist_roll_joint": 0.0,
        "waist_pitch_joint": 0.0,
        "left_shoulder_pitch_joint": 0.2,
        "left_shoulder_roll_joint": 0.2,
        "left_shoulder_yaw_joint": 0.0,
        "left_elbow_joint": 1.28,
        "left_wrist_roll_joint": 0.0,
        "left_wrist_pitch_joint": 0.0,
        "left_wrist_yaw_joint": 0.0,
        "right_shoulder_pitch_joint": 0.2,
        "right_shoulder_roll_joint": -0.2,
        "right_shoulder_yaw_joint": 0.0,
        "right_elbow_joint": 1.28,
        "right_wrist_roll_joint": 0.0,
        "right_wrist_pitch_joint": 0.0,
        "right_wrist_yaw_joint": 0.0,
    }
    env_cfg = {
        "num_actions": len(leg_joints) + len(upper_joints),
        "dt": 0.005,
        "control_decimation": 4,
        "substeps": 10,
        "episode_length_s": 8.0,
        "simulate_action_latency": True,
        "clip_actions": 1.0,
        "action_scale": 0.45,
        "action_scales": None,
        "action_scale_from_joint_limits": True,
        "action_scale_safety": 0.8,
        "action_scale_limits": {
            "left_hip_pitch_joint": 0.60,
            "left_hip_roll_joint": 0.35,
            "left_hip_yaw_joint": 0.35,
            "left_knee_joint": 0.50,
            "left_ankle_pitch_joint": 0.30,
            "left_ankle_roll_joint": 0.18,
            "right_hip_pitch_joint": 0.60,
            "right_hip_roll_joint": 0.35,
            "right_hip_yaw_joint": 0.35,
            "right_knee_joint": 0.50,
            "right_ankle_pitch_joint": 0.30,
            "right_ankle_roll_joint": 0.18,
            "waist_yaw_joint": 0.35,
            "waist_roll_joint": 0.25,
            "waist_pitch_joint": 0.25,
            "left_shoulder_pitch_joint": 0.50,
            "left_shoulder_roll_joint": 0.45,
            "left_shoulder_yaw_joint": 0.45,
            "left_elbow_joint": 0.45,
            "left_wrist_roll_joint": 0.35,
            "left_wrist_pitch_joint": 0.25,
            "left_wrist_yaw_joint": 0.25,
            "right_shoulder_pitch_joint": 0.50,
            "right_shoulder_roll_joint": 0.45,
            "right_shoulder_yaw_joint": 0.45,
            "right_elbow_joint": 0.45,
            "right_wrist_roll_joint": 0.35,
            "right_wrist_pitch_joint": 0.25,
            "right_wrist_yaw_joint": 0.25,
        },
        "base_init_pos": [0.0, 0.0, 0.79],
        "base_init_quat": [1.0, 0.0, 0.0, 0.0],
        "base_init_pos_relative_to_trampoline": True,
        "base_init_clearance": 0.02,
        "robot_mjcf": "g1.xml",
        "use_trampoline_contact_mjcf": True,
        "robot_friction": 1.4,
        "robot_foot_radius": 0.025,
        "feet_link_names": ("left_ankle_roll_link", "right_ankle_roll_link"),
        "feet_cloth_obs_radius": 0.12,
        "joint_names": leg_joints + upper_joints,
        "locked_joint_names": [],
        "default_joint_angles": default_joint_angles,
        "kp": {
            "left_hip_pitch_joint": 75.0,
            "left_hip_roll_joint": 75.0,
            "left_hip_yaw_joint": 75.0,
            "left_knee_joint": 75.0,
            "left_ankle_pitch_joint": 20.0,
            "left_ankle_roll_joint": 20.0,
            "right_hip_pitch_joint": 75.0,
            "right_hip_roll_joint": 75.0,
            "right_hip_yaw_joint": 75.0,
            "right_knee_joint": 75.0,
            "right_ankle_pitch_joint": 20.0,
            "right_ankle_roll_joint": 20.0,
            "waist_yaw_joint": 75.0,
            "waist_roll_joint": 75.0,
            "waist_pitch_joint": 75.0,
            "left_shoulder_pitch_joint": 75.0,
            "left_shoulder_roll_joint": 75.0,
            "left_shoulder_yaw_joint": 75.0,
            "left_elbow_joint": 75.0,
            "left_wrist_roll_joint": 20.0,
            "left_wrist_pitch_joint": 20.0,
            "left_wrist_yaw_joint": 20.0,
            "right_shoulder_pitch_joint": 75.0,
            "right_shoulder_roll_joint": 75.0,
            "right_shoulder_yaw_joint": 75.0,
            "right_elbow_joint": 75.0,
            "right_wrist_roll_joint": 20.0,
            "right_wrist_pitch_joint": 20.0,
            "right_wrist_yaw_joint": 20.0,
        },
        "kd": 2.0,
        "action_rate_weights": {
            "left_hip_pitch_joint": 1.0,
            "left_hip_roll_joint": 1.0,
            "left_hip_yaw_joint": 1.0,
            "left_knee_joint": 1.0,
            "left_ankle_pitch_joint": 1.0,
            "left_ankle_roll_joint": 1.0,
            "right_hip_pitch_joint": 1.0,
            "right_hip_roll_joint": 1.0,
            "right_hip_yaw_joint": 1.0,
            "right_knee_joint": 1.0,
            "right_ankle_pitch_joint": 1.0,
            "right_ankle_roll_joint": 1.0,
            "waist_yaw_joint": 2.0,
            "waist_roll_joint": 2.0,
            "waist_pitch_joint": 2.0,
            "left_shoulder_pitch_joint": 4.0,
            "left_shoulder_roll_joint": 4.0,
            "left_shoulder_yaw_joint": 4.0,
            "left_elbow_joint": 4.0,
            "left_wrist_roll_joint": 4.0,
            "left_wrist_pitch_joint": 4.0,
            "left_wrist_yaw_joint": 4.0,
            "right_shoulder_pitch_joint": 4.0,
            "right_shoulder_roll_joint": 4.0,
            "right_shoulder_yaw_joint": 4.0,
            "right_elbow_joint": 4.0,
            "right_wrist_roll_joint": 4.0,
            "right_wrist_pitch_joint": 4.0,
            "right_wrist_yaw_joint": 4.0,
        },
        "dof_vel_weights": {
            "left_hip_pitch_joint": 1.0,
            "left_hip_roll_joint": 1.0,
            "left_hip_yaw_joint": 1.0,
            "left_knee_joint": 1.0,
            "left_ankle_pitch_joint": 1.0,
            "left_ankle_roll_joint": 1.0,
            "right_hip_pitch_joint": 1.0,
            "right_hip_roll_joint": 1.0,
            "right_hip_yaw_joint": 1.0,
            "right_knee_joint": 1.0,
            "right_ankle_pitch_joint": 1.0,
            "right_ankle_roll_joint": 1.0,
            "waist_yaw_joint": 2.0,
            "waist_roll_joint": 2.0,
            "waist_pitch_joint": 2.0,
            "left_shoulder_pitch_joint": 3.0,
            "left_shoulder_roll_joint": 3.0,
            "left_shoulder_yaw_joint": 3.0,
            "left_elbow_joint": 3.0,
            "left_wrist_roll_joint": 3.0,
            "left_wrist_pitch_joint": 3.0,
            "left_wrist_yaw_joint": 3.0,
            "right_shoulder_pitch_joint": 3.0,
            "right_shoulder_roll_joint": 3.0,
            "right_shoulder_yaw_joint": 3.0,
            "right_elbow_joint": 3.0,
            "right_wrist_roll_joint": 3.0,
            "right_wrist_pitch_joint": 3.0,
            "right_wrist_yaw_joint": 3.0,
        },
        "similar_to_default_weights": {
            "left_hip_pitch_joint": 1.0,
            "left_hip_roll_joint": 1.0,
            "left_hip_yaw_joint": 1.0,
            "left_knee_joint": 1.0,
            "left_ankle_pitch_joint": 1.0,
            "left_ankle_roll_joint": 1.0,
            "right_hip_pitch_joint": 1.0,
            "right_hip_roll_joint": 1.0,
            "right_hip_yaw_joint": 1.0,
            "right_knee_joint": 1.0,
            "right_ankle_pitch_joint": 1.0,
            "right_ankle_roll_joint": 1.0,
            "waist_yaw_joint": 3.0,
            "waist_roll_joint": 3.0,
            "waist_pitch_joint": 3.0,
            "left_shoulder_pitch_joint": 5.0,
            "left_shoulder_roll_joint": 5.0,
            "left_shoulder_yaw_joint": 5.0,
            "left_elbow_joint": 5.0,
            "left_wrist_roll_joint": 5.0,
            "left_wrist_pitch_joint": 5.0,
            "left_wrist_yaw_joint": 5.0,
            "right_shoulder_pitch_joint": 5.0,
            "right_shoulder_roll_joint": 5.0,
            "right_shoulder_yaw_joint": 5.0,
            "right_elbow_joint": 5.0,
            "right_wrist_roll_joint": 5.0,
            "right_wrist_pitch_joint": 5.0,
            "right_wrist_yaw_joint": 5.0,
        },
        "lock_kp": {
            "waist_yaw_joint": 75.0,
            "waist_roll_joint": 75.0,
            "waist_pitch_joint": 75.0,
            "left_shoulder_pitch_joint": 75.0,
            "left_shoulder_roll_joint": 75.0,
            "left_shoulder_yaw_joint": 75.0,
            "left_elbow_joint": 75.0,
            "left_wrist_roll_joint": 20.0,
            "left_wrist_pitch_joint": 20.0,
            "left_wrist_yaw_joint": 20.0,
            "right_shoulder_pitch_joint": 75.0,
            "right_shoulder_roll_joint": 75.0,
            "right_shoulder_yaw_joint": 75.0,
            "right_elbow_joint": 75.0,
            "right_wrist_roll_joint": 20.0,
            "right_wrist_pitch_joint": 20.0,
            "right_wrist_yaw_joint": 20.0,
        },
        "lock_kd": 2.0,
        "termination_if_roll_greater_than": 25.0,
        "termination_if_pitch_greater_than": 25.0,
        "termination_if_xy_greater_than": 0.45,
        "termination_if_base_lower_than": 0.80,
        "max_collision_pairs": 120,
        "constraint_timeconst": 0.008,
        "show_ground": True,
        "ground_collision": False,
        "ground_reflection": True,
        "ground_z": -0.04,
        "ground_size": (8.0, 8.0),
        "ground_tile_size": (0.5, 0.5),
        "ground_friction": 1.0,
        "ground_color": (0.48, 0.52, 0.50, 1.0),
        "sky_background_color": (0.58, 0.72, 0.88),
        "ambient_light": (0.35, 0.38, 0.42),
        "enable_robot_trampoline_coupling": True,
        "robot_coup_friction": 1.8,
        "robot_coup_softness": 0.006,
        "robot_coup_links": ("left_ankle_roll_link", "right_ankle_roll_link"),
        "trampoline_file": "trampoline_v93.obj",
        "trampoline_center_radius": 0.25,
        "trampoline_outer_fix_width": 0.08,
        "enable_trampoline_support": True,
        "trampoline_support_visualization": False,
        "trampoline_support_radius": 0.86,
        "trampoline_support_edge_margin": 0.08,
        "trampoline_support_height": 0.035,
        "trampoline_support_top_offset": -0.25,
        "trampoline_support_friction": 1.4,
        "outer_ring_vertex_counts": {
            "trampoline.obj": 64,
            "trampoline_v93.obj": 16,
            "trampoline_v176.obj": 32,
        },
        "trampoline_particle_size": 0.02,
        "trampoline_self_collision": False,
        "trampoline_rigid_friction": True,
        "pbd_stretch_iterations": 10,
        "pbd_bending_iterations": 0,
        "trampoline_rho": 4.0,
        "trampoline_static_friction": 0.8,
        "trampoline_kinetic_friction": 0.6,
        "trampoline_stretch_compliance": 1.0e-7,
        "trampoline_bending_compliance": 1.0e-5,
        "trampoline_stretch_relaxation": 0.65,
        "trampoline_bending_relaxation": 0.2,
        "trampoline_air_resistance": 5.0e-5,
    }
    obs_cfg = {
        "obs_scales": {
            "ang_vel": 0.25,
            "height": 5.0,
            "lin_vel_z": 0.4,
            "xy": 2.0,
            "feet_cloth_height": 5.0,
            "feet_cloth_vel_z": 0.5,
            "dof_pos": 1.0,
            "dof_vel": 0.05,
        },
    }
    reward_cfg = {
        "flight_height_target": 0.10,
        "standing_height_offset": -0.04,
        "standing_height_sigma": 0.08,
        "height_tracking_sigma": 0.08,
        "takeoff_vel": 1.0,
        "vel_tracking_sigma": 1.0,
        "apex_vel_sigma": 0.7,
        "centering_sigma": 0.12,
        "reward_scales": {
            "alive": 1.0,
            "standing_height": 4.0,
            "centering": 1.5,
            "upright": -4.0,
            "lin_vel_xy": -1.5,
            "lin_vel_z": -2.0,
            "ang_vel_xy": -0.4,
            "action_rate": -0.04,
            "dof_vel": -0.001,
            "dof_acc": -1.0e-7,
            "similar_to_default": -0.04,
        },
    }
    command_cfg = {}
    return env_cfg, obs_cfg, reward_cfg, command_cfg


def _demo_actions(env, mode, step):
    actions = torch.zeros((env.num_envs, env.num_actions), dtype=gs.tc_float, device=gs.device)
    if mode == "sine":
        phase = math.sin(2.0 * math.pi * step * env.dt / 0.7)
        actions[:, [0, 6]] = -0.35 * phase
        actions[:, [3, 9]] = 0.85 * phase
        actions[:, [4, 10]] = -0.45 * phase
    return actions


def main():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--cpu", action="store_true", default=False)
    parser.add_argument("--num_steps", type=int, default=2000)
    parser.add_argument("--motion", choices=["zero", "sine"], default="zero")
    parser.add_argument("--trampoline", choices=["trampoline_v93.obj", "trampoline_v176.obj"])
    parser.add_argument("--show-support", action="store_true", default=False)
    parser.add_argument("--no-support", action="store_true", default=False)
    parser.add_argument("--no-ground", action="store_true", default=False)
    parser.add_argument("--ground-collision", action="store_true", default=False)
    parser.add_argument("--dt", type=float)
    parser.add_argument("--substeps", type=int)
    parser.add_argument("--stretch-compliance", type=float)
    parser.add_argument("--bending-compliance", type=float)
    parser.add_argument("--support-offset", type=float)
    args = parser.parse_args()

    gs.init(backend=gs.cpu if args.cpu else gs.gpu, precision="32", logging_level="warning")
    env_cfg, obs_cfg, reward_cfg, command_cfg = get_default_cfgs()
    if args.trampoline is not None:
        env_cfg["trampoline_file"] = args.trampoline
    if args.show_support:
        env_cfg["trampoline_support_visualization"] = True
    if args.no_support:
        env_cfg["enable_trampoline_support"] = False
    if args.no_ground:
        env_cfg["show_ground"] = False
    if args.ground_collision:
        env_cfg["ground_collision"] = True
    if args.dt is not None:
        env_cfg["dt"] = args.dt
    if args.substeps is not None:
        env_cfg["substeps"] = args.substeps
    if args.stretch_compliance is not None:
        env_cfg["trampoline_stretch_compliance"] = args.stretch_compliance
    if args.bending_compliance is not None:
        env_cfg["trampoline_bending_compliance"] = args.bending_compliance
    if args.support_offset is not None:
        env_cfg["trampoline_support_top_offset"] = args.support_offset

    env = G1TrampolineEnv(
        num_envs=1,
        env_cfg=env_cfg,
        obs_cfg=obs_cfg,
        reward_cfg=reward_cfg,
        command_cfg=command_cfg,
        show_viewer=True,
    )
    env.reset()

    with torch.no_grad():
        for step in range(args.num_steps):
            env.step(_demo_actions(env, args.motion, step))


if __name__ == "__main__":
    main()
